name: Go

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.16', '1.17']
    steps:
      - name: Setup Go
        with:
          go-version: ${{ matrix.go }}
        uses: actions/setup-go@v2
        
      - uses: actions/checkout@v2
      
      - name: Test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=github.com/Yiling-J/piper,github.com/Yiling-J/piper/cmd,github.com/Yiling-J/piper/integration ./...
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
